<a href="https://colab.research.google.com/github/omar134-a/skills-introduction-to-github/blob/main/project_BI_METHODS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Step 1 Load the CSV file**

In [ ]:
import pandas as pd
df = pd.read_csv('/content/chunk_0017.csv')
df['full_text'] = df['title'].fillna('') + ' ' + df['content'].fillna('')
df.head()

,label,title,content,full_text
0,0,Pretty Cheesy for Monster,Normally I've been really happy with Monster p...,Pretty Cheesy for Monster Normally I've been r...
1,0,wolf ticket,not effective. I tore one of the sheets unfold...,wolf ticket not effective. I tore one of the s...
2,0,not good topper,i bought this product thinking that it will so...,not good topper i bought this product thinking...
3,1,One of the best cookbooks I've ever used,I received this as a gift from a friend who kn...,One of the best cookbooks I've ever used I rec...
4,1,Amazing,I love this DVD. Even though you can view Dr. ...,Amazing I love this DVD. Even though you can v...

# **step 2 preprocessing**

In [10]:
import nltk
import string
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('stopwords')

def preprocess_text(text):
    text = text.lower()
    text = ''.join([char for char in text if char not in string.punctuation and not char.isdigit()])

    tokens = text.split()
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(word) for word in tokens]

    return " ".join(tokens)
df['processed_text'] = df['full_text'].apply(preprocess_text)
df[['label', 'processed_text']].head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

   label                                     processed_text
0      0  pretti cheesi monster normal ive realli happi ...
1      0  wolf ticket effect tore one sheet unfold could...
2      0  good topper bought product think solv softi ma...
3      1  one best cookbook ive ever use receiv gift fri...
4      1  amaz love dvd even though view dr horribl sing...

# **step 3 text to number ( bag of words )**

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
Vectorizer = CountVectorizer()
X = Vectorizer.fit_transform(df['processed_text'])
Y = df['label']

# step 4 train naive bayes model

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

X_train,X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

model = MultinomialNB()
model.fit(X_train,y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.85

# **omar malas**

# **202310833**